### ISSUE TITLE
req.resume is not a function at send

### ISSUE THREAD

**Issue by crazy4groovy** [howardabrams/node-mocks-http#184]
Has anyone seen this error before? I am not certain what is causing it in my call stack

```
(node:16) UnhandledPromiseRejectionWarning: TypeError: req.resume is not a function
at send (/usr/app/node_modules/finalhandler/index.js:310:7)
at /usr/app/node_modules/finalhandler/index.js:133:5
at /usr/app/node_modules/express/lib/router/index.js:635:15
at next (/usr/app/node_modules/express/lib/router/index.js:210:14)
at Function.handle (/usr/app/node_modules/express/lib/router/index.js:174:3)
at Function.handle (/usr/app/node_modules/express/lib/application.js:174:10)
at app (/usr/app/node_modules/express/lib/express.js:39:9)
at /usr/app/dist/fargate-nest.js:28:9
```

I am using NestJS, which should be express-compatible. Here is my calling code.

```
  const req = httpMocks.createRequest({method: 'GET'});
  const res = httpMocks.createResponse();
  // execute NestJS App
  expressApp(req, res);
```

**Comment by AndyOGo** [comment]
@crazy4groovy a quick search for `resume` does not show an available `req.resume` function:
https://github.com/expressjs/express/search?q=resume&unscoped_q=resume
