### ISSUE TITLE
 Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by mustapha-wang** [howardabrams/node-mocks-http#53]
node.js：0.10.24
express:4.12.3
express-session:1.10.4
body-parser：1.12.1
cookie-parser:1.3.4
node-mocks-http：1.2.7

at Function.proto.process_params (/home/bae/app/node_modules/express/lib/router/index.js:321:12)
 at /home/bae/app/node_modules/express/lib/router/index.js:270:7
 at trim_prefix (/home/bae/app/node_modules/express/lib/router/index.js:300:13)
 at Layer.handle_error (/home/bae/app/node_modules/express/lib/router/layer.js:54:12)
 at next (/home/bae/app/node_modules/express/lib/router/index.js:246:14)
 at /home/bae/app/node_modules/express/lib/router/index.js:603:15
 at /home/bae/app/node_modules/express/node_modules/finalhandler/index.js:96:5
 at send (/home/bae/app/node_modules/express/node_modules/finalhandler/index.js:135:3)
 at unpipe (/home/bae/app/node_modules/express/node_modules/finalhandler/index.js:153:12)
 at IncomingMessage.Readable.unpipe (_stream_readable.js:633:12)
 TypeError: Cannot read property 'pipesCount' of undefined

**Comment by JohnnyEstilles** [comment]
@mustapha-wang, can you share the code of your test/spec and the handler you're testing? I don't see `node-mocks-http` anywhere in your tack trace, so I'm not quite sure I understand the issue you're reporting.

**Comment by JohnnyEstilles** [comment]
@mustapha-wang, I'm closing this issue for now. You did not provide us with enough info to reproduce the error. Feel free to re-open and provide additional information.

**Comment by NIM-Pro** [comment]
Please, reopen issue. I got the same error.
Code:
```javascript
'use strict'

const Fs = require('fs')
const HttpMocks = require('node-mocks-http')
const StreamToPromise = require('stream-to-promise')
const Stream = require('stream')
const Express = require('express')
const EventEmitter = require('events')

let app = Express()
app.all((req, res)=> {
	res.end('Hello, world!')
})

function testRequest() {
	let req = HttpMocks.createRequest({
		url: '/'
	})
	let res = HttpMocks.createResponse({
		eventEmitter: EventEmitter,
		writableStream: Stream.PassThrough
	})
	app(req, res)
	return StreamToPromise(res)
}

testRequest()
.then(data=> console.log(data))
.catch(err=> console.log(err.stack || err))
```

Error stack:
```
TypeError: Cannot read property 'pipesCount' of undefined
    at IncomingMessage.Readable.unpipe (_stream_readable.js:611:12)
    at unpipe (C:\Users\NotIntMan\Desktop\MEAN\test2\node_modules\unpipe\index.js:47:12)
    at send (C:\Users\NotIntMan\Desktop\MEAN\test2\node_modules\finalhandler\index.js:146:3)
    at Immediate.<anonymous> (C:\Users\NotIntMan\Desktop\MEAN\test2\node_modules\finalhandler\index.js:107:5)
    at Immediate.<anonymous> (C:\Users\NotIntMan\Desktop\MEAN\test2\node_modules\express\lib\router\index.js:618:15)
    at Immediate.immediate._onImmediate (timers.js:435:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by yisraelx** [comment]
I think it happens when: 
Incoming request => Page not found => Express tries to return a 404 error => This error occurs

**Comment by diasdavid** [comment]
Any update on why this error happens? Thank you

**Comment by nabilfreeman** [comment]
Came here from Google...

I also had this error when encountering a 404 in https://github.com/AminaG/node-run-middleware. Thus it may be lower-level code in a shared dependency rather than this module.

**Comment by SeanHayes** [comment]
I get this error when using the following middleware on a mock request:
```module.exports = function(req, res, next) {
    req.rawBody = '';

    req.on('data', function(chunk) { 
        req.rawBody += chunk;
    });

    next();
}
```
```
app.use(rawBody);
```

If I comment out `req.on*` my test passes.
